name: Build Udroid Ubuntu Plucky amd64

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential binfmt-support qemu-user-static debootstrap -y

      - name: Run Build Script
        run: |
          chmod +x build.sh
          sudo ./build.sh -s plucky -v raw -a amd64
          
          - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-plucky-amd64
          path: out/plucky-raw-amd64.tar.gz
